### ISSUE TITLE
IOS archiving taking too much time.

### ISSUE THREAD

**Issue by farhanlatheef** [webex/webex-ios-sdk#36] opened 2019-09-24 05:24 UTC
Since switching from SparkSDK to WebexSDK even though normal build time is ok, while archiving it take too much time. Sometimes over an hour!.

**Comment by farhanlatheef** [comment] 2019-10-20 07:39
any update on this?.

**Comment by MrShiY** [comment] 2019-10-23 07:50
@farhanlatheef  what's the result?

**Comment by olivierproffit** [comment] 2019-10-29 18:10
@farhanlatheef  we are closing the issue since we can't reproduce it. Please let us know if it persists so that they further investigate.

**Closed by olivierproffit** 2019-10-29 18:10 UTC
